version: '2'

services:
    zookeeper1:
        container_name: zookeeper1
        hostname: zookeeper1
        image: hyperledger/fabric-zookeeper
        restart: always
        environment:
            - ZOO_MY_ID=1
            - ZOO_SERVERS=server.1=zookeeper1:2888:3888 server.2=zookeeper2:2888:3888 server.3=zookeeper3:2888:3888

        ports:
            - "2181:2181"
            - "2888:2888"
            - "3888:3888"
        extra_hosts:
            - "zookeeper1:[A ip]"
            - "zookeeper2:[B ip]"
            - "zookeeper3:[B ip]"
            - "kafka1:[A ip]"
            - "kafka2:[B ip]"
            - "kafka3:[B ip]"
